config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => "auth", :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { registrations: 'registrations' }
  
  get 'speakers/contact'

  get 'orders/new'

  get 'orders/index'

  get 'orders/show'

  get 'static_pages/landing_page'

  resources :users

  resources :payments

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

	def average_rating
		comments.average(:rating).to_f
	end

	# number of Product sold
	def scored(sold)
    if sold > self.high_score
      $redis.zadd("highscores", sold, self.id)
    end
  end
  
	# rank (popularity) of product
  def rank
    $redis.zrevrank("highscores", self.id) + 1
  end
  
	# highest number of Product sold
  def high_score
    $redis.zscore("highscores", self.id).to_i
  end
  
  # top three Products sold
  def self.top_3
    $redis.zrevrange("highscores", 0, 2).map{|id| Product.find(id)}
  end

	validates :name, presence: true
	  validates :description, presence: true
	  validates :image_url, presence: true
	  validates :colour, presence: true
    validates :price, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource :except => [:index, :show]
  respond_to :json, :html  
  # GET /products
  # GET /products.json
  
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.development?
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.where("name ilike ?", "%#{search_term}%")
      end  
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
	  <div class="row">
	  	<h3><span class="glyphicon glyphicon-pushpin"></span></h3>
	  	<p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>

      <% if signed_in? && current_user.admin? %>
		  	<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product,comment), method: :delete, data: { confirm: 'Are you sure?' } %>
		  <% end %>

		  </p>

	  	<p><%= comment.body %></p>

	  </div><!-- /row -->
	  <div class="rated" data-score="<%= comment.rating %>"></div>
	<% end %>

	
</div><!-- /product-reviews -->

app/views/products/_form.html.erb
<div class="container-fluid product_info">
  <h2><%= @product.name %></h2>

  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url %>
    </div>
    <div class="field">
      <%= f.label :colour %><br>
      <%= f.text_field :colour %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      $<%= f.text_field :price, type: "number" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div><!-- /container-fluid -->

app/views/products/_new_comment.html.erb
<div class="add_comment">
  <% if signed_in? %>
    <h4>Add a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <p>
        <%= f.label :body, "Comment:" %><br>
        <%= f.text_area :body %>
      </p>

      <h5>Select Rating</h5>
      	<div class="rating"></div>

      <p>
      	<%= f.submit "Submit" %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="container-fluid products_index">
  <div class="row" id="product_list">
      <% cache(product) do %>
        <div class="col-xs-12 col-s-3 col-md-2"><%= product.name %></div>
        <div class="col-xs-12 col-s-3 col-md-2"><%= product.description %></div>
        <div class="col-xs-12 col-s-3 col-md-2"><%= product.image_url %></div> 
        <div class="col-xs-12 col-s-3 col-md-2"><%= product.colour %></div>
        <div class="col-xs-12 col-s-3 col-md-2">$<%= product.price %></div>
      <% end %>  

    <div class="col-xs-12 col-s-3 col-md-2">
      <%= link_to 'Show', product %>
      <% if signed_in? && current_user.admin? %>
        ||<%= link_to 'Edit', edit_product_path(product) %>||
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>  
    </div>
  </div><!-- /row -->
</div><!-- /container-fluid -->

app/views/products/edit.html.erb
<%= render 'form' %>

<%= link_to 'Return without saving', products_path %>

app/views/products/index.html.erb
<div class ="container-fluid products_index">
    <h1>Products Listing</h1>
    
    <% if signed_in? && current_user.admin? %>
      <h4><%= link_to 'Create New Product', new_product_path %></h4>
    <% end %>

    <div class="row" id="product_list">
      <div class="col-xs-12 col-s-3 col-md-2">
        <h4>Name</h4>
      </div>
      <div class="col-xs-12 col-s-3 col-md-2">
        <h4>Description</h4>
      </div>
      <div class="col-xs-12 col-s-3 col-md-2">
        <h4>Image URL</h4>
      </div>
      <div class="col-xs-12 col-s-3 col-md-2">
        <h4>Colour</h4>
      </div>
      <div class="col-xs-12 col-s-3 col-md-2">
        <h4>Price</h4>
      </div>
      <div class="col-xs-12 col-s-3 col-md-2">
        <h4></h4>
      </div> 
    </div><!-- /row -->


    <%= render @products %>

  <br>
  </div> <!-- /container-fluid -->

app/views/products/new.html.erb
<div class="new_product_page">

 <h2>New Product</h2>

	<%= render 'form' %>

	<%= link_to 'Return without saving', products_path %>
	
</div>

app/views/products/show.html.erb
<div class="container-fluid" id="show_product">
  <div class="row">

    <div class="col-xs-12 col-md-4" id="thumbnails">
      <a href="#" class="thumbnail">
        <%= image_tag(@product.image_url, class: "img-zoom", data_zoom_image: @product.image_url) %>
      </a>
      <p>Roll over image to zoom</p>
      <% if signed_in? && current_user.admin? %>
        <p><%= link_to 'Edit Product', edit_product_path(@product) %> | <%= link_to 'Back', products_path %></p>
      <% end %>
    </div><!-- /col -->

    <div class="col-xs-12 col-md-4" >
      <h6>
        <strong>Name:</strong>
        <%= @product.name %>
      </h6>

      <h6>
        <strong>Description:</strong>
        <%= @product.description %>
      </h6>

      <h6>
        <strong>Image url:</strong>
        <%= @product.image_url %>
      </h6>

      <h6>
        <strong>Color:</strong>
        <%= @product.colour %>
      </h6>

      <h6>
        <strong>Price:</strong>
        $<%= @product.price %>
      </h6>

      <h6>Average Rating:</h6><div class="rated" data-score="<%= @product.average_rating %>"></div>

      <%= form_tag "/payments/create" do %>
      <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>
    </div><!-- /col -->

    <div class="col-xs-12 col-md-4">
      <%= render 'new_comment' %>
    </div><!-- /col -->

  </div><!-- /row -->

  <hr>

  <%= render 'comments' %>

  <%= will_paginate @comments %>
</div><!-- /container -->