config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => "auth", :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { registrations: 'registrations' }
  
  get 'speakers/contact'

  get 'orders/new'

  get 'orders/index'

  get 'orders/show'

  get 'static_pages/landing_page'

  resources :users

  resources :payments

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="shop">
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Deep Sea Kayaks</title>

  <link href='https://fonts.googleapis.com/css?family=Oxygen:300,700' rel='stylesheet' type='text/css'>

  <%= favicon_link_tag 'site_icon.png' %>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>

<body >
	<nav class="navbar" role="navigation">
	  <nav class="container">
	    <nav class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">MENU</button>
	    </nav><!-- /navbar-header -->          
	    <nav class="navbar-collapse collapse">
	      <ul class="left_links nav navbar-nav"> 
	        <li>
	        	<a class="btn btn-default navbar-btn" role="button"
	      		<% if user_signed_in? %>
	      		  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
	      		<% else %>
	      		  <%= link_to('Login', new_user_session_path) %>
	      		><% end %>
	      		</a>
	      	</li>
	      	<li id="edit_user_info">
	      		<% if user_signed_in? %>
	      		  <%= link_to('Edit Account', edit_user_registration_path) %>
	      		<% else %>
	      		  <%= link_to('Sign Up', new_user_registration_path) %>
	      		<% end %>
	      	</li>
	      </ul>           
	      <ul class="right_links nav navbar-nav">
	      	<li><%= link_to "Featured Items", static_pages_landing_page_path %></li> 
	        <li><%= link_to "Products Listing", products_path %></li>
	        <li><%= link_to "About", static_pages_about_path %></li>
	        <li><%= link_to "Contact", static_pages_contact_path %></li>
	        <li><%= link_to "Homepage", static_pages_index_path %></a></li>    
	      </ul><!-- /nav navbar-nav -->     
	    </nav><!-- /navbar-collapse collapse -->
	  </nav><!-- /container-fluid -->
	</nav><!-- /navbar -->


  <% if notice %>
  <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  	<%= alert %>
  </div><!-- /alert -->
  <% end %>

<%= yield %>

	<footer class="admin_footer">
	  <p>Admin links:&nbsp;&nbsp;<%= link_to "Show All Orders", orders_path %> |
		<%= link_to "Show All Users", users_path %></p>
	</footer>


  <!-- jQuery Script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

  <!-- Bootstrap core JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>